language: php
php:
  - '7.0'
  - '7.1'

before_install:
  - pecl channel-update pecl.php.net
  - (CFLAGS="-O1 -g3 -fno-strict-aliasing"; pecl install yaml < /dev/null &)

install:
  - composer install --no-dev
  - composer update --no-dev
