#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';

use Symfony\Component\Console\Application;
use Symfony\Component\Console\Input\InputOption;
use Project\Configuration;

$application = new Application();
$application->config = new Configuration();

$definition = $application->getDefinition();
$definition->addOption(
  new InputOption(
    'environment',
    'e',
    InputOption::VALUE_OPTIONAL,
    'The environment to operate in.'
  )
);
$definition->addOption(
  new InputOption(
    'no-execute',
    'x',
    InputOption::VALUE_OPTIONAL,
    'Output the command but do not run it'
  )
);

// find commands in src/Command
$commands = $application->config->getCommands();

foreach ($commands as $command) {
  if (is_array($command)) {
    $class = $command[0];
    $args = array_slice($command, 1);
    $application->add(new $class(...$args));
    continue;
  }

  try {
    $application->add(new $command());
  }
  catch (Symfony\Component\Console\Exception\LogicException $e) {
  }
}

$application->run();
