#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';

use Symfony\Component\Console\Application;
use Symfony\Component\Console\Input\InputOption;
use Project\Configuration;

$application = new Application();
$application->config = new Configuration();

$application->getDefinition()->addOption(
  new InputOption(
    'environment',
    'e',
    InputOption::VALUE_OPTIONAL,
    'The environment to operate in.'
  )
);

// find commands in src/Command
$commands = $application->config->getCommands();

foreach ($commands as $command) {
  $application->add(new $command());
}

$application->run();
