local:
  # local.default is applied to all components (if local.components
  # is defined). If local.components does not exist, this is the
  # environment that would be run right "local:run" or
  # "local:run default"
  default:
    style: vagrant

  components:

    # this will inherit local.default.style
    default:
      base: $PROJECT/vagrant
      # you can setup things to run before local:start and local:stop. Also
      # you can use "post" to run things after local:start and local:stop.
      pre:
        - command: rm $PROJECT/build/logs/*.log

    # this will override local.default.style for a "script". Scripts
    # should be executeable.
    #
    frontend:
      style: script
      script: $PROJECT/server.js

      # NOTE: "script" and "command" runners are considered "start only"
      # meaning that they only support "local:start" and not "local:stop". 
      # If you want a script or command to work with "local:stop" you can 
      # turn on the stoppable flag. You can also set a stop_script or a 
      # stop_command option for specific scripts or commands to run instead.
      #
      # stoppable: true
      # stop_script: $PROJECT/stop_server.js
    
    docker_compose:
      style: docker-compose
      # will cause docker-compose to run with the -f flag
      file: docker-compose.dev.yml
      # turn off "detached" mode
      detached: false
